// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHfz0p633QfZM0OcfV5Pqj66jAtzWRkv0',
    appId: '1:354258887527:web:d6e0ab4d48b0031613c5c2',
    messagingSenderId: '354258887527',
    projectId: 'eutruco-13cc8',
    authDomain: 'eutruco-13cc8.firebaseapp.com',
    databaseURL: 'https://eutruco-13cc8-default-rtdb.firebaseio.com',
    storageBucket: 'eutruco-13cc8.appspot.com',
    measurementId: 'G-E10SLNW1Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4s0_L1ucG-rwh5TNzZl-wfmIJ7Md3bb4',
    appId: '1:354258887527:android:540d31861e9e536c13c5c2',
    messagingSenderId: '354258887527',
    projectId: 'eutruco-13cc8',
    databaseURL: 'https://eutruco-13cc8-default-rtdb.firebaseio.com',
    storageBucket: 'eutruco-13cc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCltGkWtRF7Qk84nXCKvG2npiP1piCqW1g',
    appId: '1:354258887527:ios:c0906f916535c8ec13c5c2',
    messagingSenderId: '354258887527',
    projectId: 'eutruco-13cc8',
    databaseURL: 'https://eutruco-13cc8-default-rtdb.firebaseio.com',
    storageBucket: 'eutruco-13cc8.appspot.com',
    iosBundleId: 'com.example.euTruco',
  );

}